/*
Electric Flower Co. Master Show Data

Generated automatically from schedule.html.
Total shows: 254

Edit individual show records here after conversion.
All website widgets can read from window.EFC_SHOWS.
*/

window.EFC_SHOWS = [
  {
    "id": "show-2026-11-07-012",
    "date": "2026-11-07",
    "venue": "Burr Oak Dance Club",
    "city": "Burr Oak",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-10-17-011",
    "date": "2026-10-17",
    "venue": "The Irish Pub",
    "city": "Lansing",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-10-09-010",
    "date": "2026-10-09",
    "venue": "Hell Saloon",
    "city": "Pinckney",
    "state": "MI",
    "time": "8:30p-12a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-10-03-009",
    "date": "2026-10-03",
    "venue": "Private Wedding at Treetops Resort",
    "city": "Gaylord",
    "state": "MI",
    "time": "",
    "category": "Wedding",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-10-02-008",
    "date": "2026-10-02",
    "venue": "The Score",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-09-25-007",
    "date": "2026-09-25",
    "venue": "Oktoberfest @ Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-09-04-006",
    "date": "2026-09-04",
    "venue": "Private Event at Congregation Shaarey Zedek",
    "city": "Southfield",
    "state": "MI",
    "time": "5:00p-7:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-29-005",
    "date": "2026-08-29",
    "venue": "Commodore's Ball at Pentwater Yacht Club",
    "city": "Pentwater",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-22-004",
    "date": "2026-08-22",
    "venue": "Short's Brewing Company",
    "city": "Bellaire",
    "state": "MI",
    "time": "7:00p-9:30p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-13-003",
    "date": "2026-08-13",
    "venue": "Summer Concert Series @ McClintock Park",
    "city": "Laingsburg",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-08-002",
    "date": "2026-08-08",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-07-001",
    "date": "2026-08-07",
    "venue": "Gun Lake Casino",
    "city": "Wayland",
    "state": "MI",
    "time": "9:00p-12:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-08-01-013",
    "date": "2026-08-01",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-30-014",
    "date": "2026-07-30",
    "venue": "Fireside Grill",
    "city": "Novi",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-25-015",
    "date": "2026-07-25",
    "venue": "Men's Invitational at Warwick Hills Country Club",
    "city": "Granc Blanc",
    "state": "MI",
    "time": "6:00p-9:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-22-016",
    "date": "2026-07-22",
    "venue": "The Cascades Summer Concert Series",
    "city": "Jackson",
    "state": "MI",
    "time": "6:30p-8:30p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-18-017",
    "date": "2026-07-18",
    "venue": "Horns Gaslight Bar",
    "city": "Mackinac Island",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-17-018",
    "date": "2026-07-17",
    "venue": "Horns Gaslight Bar",
    "city": "Mackinac Island",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-09-019",
    "date": "2026-07-09",
    "venue": "Tunes by the Tridge",
    "city": "Midland",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-04-020",
    "date": "2026-07-04",
    "venue": "Turtle Lake Resort",
    "city": "Union City",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-07-03-021",
    "date": "2026-07-03",
    "venue": "N42 Bar & Grill @ MacRay Harbor",
    "city": "Harrison Twp",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-06-19-022",
    "date": "2026-06-19",
    "venue": "Private Party",
    "city": "Ann Arbor",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-06-13-023",
    "date": "2026-06-13",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-12:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-06-12-024",
    "date": "2026-06-12",
    "venue": "Silver Lake Chicken Shack",
    "city": "Mears",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-06-06-025",
    "date": "2026-06-06",
    "venue": "Short's Brewing Company",
    "city": "Bellaire",
    "state": "MI",
    "time": "7:00p-9:30p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-06-05-026",
    "date": "2026-06-05",
    "venue": "Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-9:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-30-027",
    "date": "2026-05-30",
    "venue": "Detroit Yacht Club",
    "city": "Detroit",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-29-028",
    "date": "2026-05-29",
    "venue": "North Peak Brewing Co. & Kilkenny's",
    "city": "Bay City",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-22-029",
    "date": "2026-05-22",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-09-030",
    "date": "2026-05-09",
    "venue": "Hell Saloon",
    "city": "Pinckney",
    "state": "MI",
    "time": "8:30p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-04-031",
    "date": "2026-05-04",
    "venue": "Star Wars Day with the Detroit Tigers @ Comerica Park",
    "city": "Detroit",
    "state": "MI",
    "time": "5:00-6:15p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-05-02-032",
    "date": "2026-05-02",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-04-10-033",
    "date": "2026-04-10",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-03-27-034",
    "date": "2026-03-27",
    "venue": "High Caliber Karting & Entertainment",
    "city": "Okemos",
    "state": "MI",
    "time": "7:30p-10:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-03-14-035",
    "date": "2026-03-14",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-03-13-036",
    "date": "2026-03-13",
    "venue": "Summerlands Brewing Co",
    "city": "Holt",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-03-07-037",
    "date": "2026-03-07",
    "venue": "Burr Oak Dance Club",
    "city": "Burr Oak",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-01-09-038",
    "date": "2026-01-09",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2026-01-03-039",
    "date": "2026-01-03",
    "venue": "Hell Saloon",
    "city": "Pinckney",
    "state": "MI",
    "time": "8:30p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-12-31-040",
    "date": "2025-12-31",
    "venue": "NYE at The Green Door",
    "city": "Lansing",
    "state": "MI",
    "time": "Doors at 7pm",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-12-26-041",
    "date": "2025-12-26",
    "venue": "Gun Lake Casino",
    "city": "Wayland",
    "state": "MI",
    "time": "9:00p-12:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-12-06-042",
    "date": "2025-12-06",
    "venue": "Flushing Moose Lodge",
    "city": "Flushing",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-11-26-043",
    "date": "2025-11-26",
    "venue": "Thanksgiving Eve at Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-11-15-044",
    "date": "2025-11-15",
    "venue": "The Roadhouse",
    "city": "Jackson",
    "state": "MI",
    "time": "8:30p-12:30am",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-11-08-045",
    "date": "2025-11-08",
    "venue": "The Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30am",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-10-18-046",
    "date": "2025-10-18",
    "venue": "The Roadhouse",
    "city": "Jackson",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-10-17-047",
    "date": "2025-10-17",
    "venue": "Private Event - Halloween Party for Willingham & Cote PC",
    "city": "East Lansing",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-10-11-048",
    "date": "2025-10-11",
    "venue": "Private Event - Block Party",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-10-10-049",
    "date": "2025-10-10",
    "venue": "Private Event - Birthday Party",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-10-04-050",
    "date": "2025-10-04",
    "venue": "Shots on the River",
    "city": "Belmont",
    "state": "MI",
    "time": "9p-1a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-09-26-051",
    "date": "2025-09-26",
    "venue": "Oktoberfest @ Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-09-20-052",
    "date": "2025-09-20",
    "venue": "Rogue River Tavern",
    "city": "Rockford",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-09-13-053",
    "date": "2025-09-13",
    "venue": "The Score",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-09-12-054",
    "date": "2025-09-12",
    "venue": "Private Event - 50th Anniversary Party",
    "city": "Petoskey",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-09-05-055",
    "date": "2025-09-05",
    "venue": "Silver Lake Chicken Shack",
    "city": "Mears",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-31-056",
    "date": "2025-08-31",
    "venue": "Turtle Lake Resort",
    "city": "Union City",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-23-057",
    "date": "2025-08-23",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-22-058",
    "date": "2025-08-22",
    "venue": "The Stables",
    "city": "Bay City",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-20-059",
    "date": "2025-08-20",
    "venue": "Summer Concert Series @ Hiram Sims Park",
    "city": "Walled Lake",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-17-060",
    "date": "2025-08-17",
    "venue": "Nine on Nine Concert Series at Schiffer Park",
    "city": "Ferndale",
    "state": "MI",
    "time": "4:00p-5:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-16-061",
    "date": "2025-08-16",
    "venue": "D-Railed Bar & Grill",
    "city": "Durand",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-13-062",
    "date": "2025-08-13",
    "venue": "Meridian Farmer's Market Summer Concert Series",
    "city": "Okemos",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-11-063",
    "date": "2025-08-11",
    "venue": "The Deck",
    "city": "Muskegon",
    "state": "MI",
    "time": "6:00p-9:00ap",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-07-064",
    "date": "2025-08-07",
    "venue": "Private Event - Freedom Boat Club 10th Anniversary Party",
    "city": "Stevenville",
    "state": "MI",
    "time": "6:00p-9:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-02-065",
    "date": "2025-08-02",
    "venue": "Detroit Yacht Club",
    "city": "Detroit",
    "state": "MI",
    "time": "8:00p-11:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-08-01-066",
    "date": "2025-08-01",
    "venue": "The Score",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-30-067",
    "date": "2025-07-30",
    "venue": "Gun Lake Live at Bay Pointe Inn",
    "city": "Shelbyville",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-28-068",
    "date": "2025-07-28",
    "venue": "Wednesday Night Live Concert Series",
    "city": "Durand",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-26-069",
    "date": "2025-07-26",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-25-070",
    "date": "2025-07-25",
    "venue": "Trak Houz @ Zeigler Motorsports",
    "city": "Kalamazoo",
    "state": "MI",
    "time": "5:00p-8:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-20-071",
    "date": "2025-07-20",
    "venue": "Cascade Hills Country Club",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "3:00pm-7:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-19-072",
    "date": "2025-07-19",
    "venue": "Private Event - Birthday",
    "city": "Pinckney",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-17-073",
    "date": "2025-07-17",
    "venue": "Opening for \"Faithfully - The Music of Journey\" | Grand Rapids Symphony Orchestra Picnic Pops @ Millenium Park | Ticket Info: https://www.grsymphony.org/family-fare-picnic-pops",
    "city": "Walker",
    "state": "MI",
    "time": "Doors at 5:45p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-12-074",
    "date": "2025-07-12",
    "venue": "Private Event - Long Lake Cloverdale Association Annual Party",
    "city": "Delton",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-11-075",
    "date": "2025-07-11",
    "venue": "Gun Lake Casino",
    "city": "Wayland",
    "state": "MI",
    "time": "10:00p-2:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-10-076",
    "date": "2025-07-10",
    "venue": "Summer Concert Series @ McClintock Park",
    "city": "Laingsburg",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-05-077",
    "date": "2025-07-05",
    "venue": "Short's Brewing Co",
    "city": "Bellaire",
    "state": "MI",
    "time": "7:00p-9:30p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-04-078",
    "date": "2025-07-04",
    "venue": "Private Party",
    "city": "Wolverine",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-07-01-079",
    "date": "2025-07-01",
    "venue": "The Deck",
    "city": "Muskegon",
    "state": "MI",
    "time": "6:00p-9:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-28-080",
    "date": "2025-06-28",
    "venue": "Private Event at Au Gres Yacht Club",
    "city": "Au Gres",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-14-081",
    "date": "2025-06-14",
    "venue": "South Haven Yacht Club",
    "city": "South Haven",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-13-082",
    "date": "2025-06-13",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-12-083",
    "date": "2025-06-12",
    "venue": "Cascade Township Summer Concert Series",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:30p-8:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-11-084",
    "date": "2025-06-11",
    "venue": "Music in the Park at Au Gres City Park",
    "city": "Au Gres",
    "state": "MI",
    "time": "6:30p-8:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-06-07-085",
    "date": "2025-06-07",
    "venue": "Annual Blessing of the Boats Event",
    "city": "Ludington",
    "state": "MI",
    "time": "TIME TBA",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-31-086",
    "date": "2025-05-31",
    "venue": "Horn's Gaslight Bar",
    "city": "Mackinac Island",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-30-087",
    "date": "2025-05-30",
    "venue": "Horn's Gaslight Bar",
    "city": "Mackinac Island",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-25-088",
    "date": "2025-05-25",
    "venue": "Silver Lake Chicken Shack",
    "city": "Mears",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-20-089",
    "date": "2025-05-20",
    "venue": "Private Event - Wedding",
    "city": "Ann Arbor",
    "state": "MI",
    "time": "",
    "category": "Wedding",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-17-090",
    "date": "2025-05-17",
    "venue": "Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-10-091",
    "date": "2025-05-10",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-05-09-092",
    "date": "2025-05-09",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-04-05-093",
    "date": "2025-04-05",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-04-04-094",
    "date": "2025-04-04",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-03-28-095",
    "date": "2025-03-28",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-03-21-096",
    "date": "2025-03-21",
    "venue": "Sherman's Lounge",
    "city": "Grand Blanc",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-02-28-097",
    "date": "2025-02-28",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-02-22-098",
    "date": "2025-02-22",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-02-21-099",
    "date": "2025-02-21",
    "venue": "Ascend Sportsbook at Soaring Eagle Casino",
    "city": "Mt. Pleasant",
    "state": "MI",
    "time": "10:00p-2:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-02-15-100",
    "date": "2025-02-15",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-01-31-101",
    "date": "2025-01-31",
    "venue": "Ascend Sportsbook at Soaring Eagle Casino",
    "city": "Mt. Pleasant",
    "state": "MI",
    "time": "10:00p-2:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-01-25-102",
    "date": "2025-01-25",
    "venue": "Opening for Dancing Queen: An ABBA Salute at Park Theatre<br>Tickets available at https://parktheatreholland.org/",
    "city": "Holland",
    "state": "MI",
    "time": "Doors at 7:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2025-01-10-103",
    "date": "2025-01-10",
    "venue": "The Green Door",
    "city": "Lansing",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-12-31-104",
    "date": "2024-12-31",
    "venue": "NYE @ Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-12-21-105",
    "date": "2024-12-21",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-12-20-106",
    "date": "2024-12-20",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-12-13-107",
    "date": "2024-12-13",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-29-108",
    "date": "2024-11-29",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-27-109",
    "date": "2024-11-27",
    "venue": "Thanksgiving Eve at Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-16-110",
    "date": "2024-11-16",
    "venue": "Vestal Inn",
    "city": "Belmont",
    "state": "MI",
    "time": "8p-12a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-09-111",
    "date": "2024-11-09",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-02-112",
    "date": "2024-11-02",
    "venue": "Private Party",
    "city": "Fowler",
    "state": "MI",
    "time": "9:30p-12:00a",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-11-01-113",
    "date": "2024-11-01",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-10-26-114",
    "date": "2024-10-26",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-10-25-115",
    "date": "2024-10-25",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-10-19-116",
    "date": "2024-10-19",
    "venue": "Cobblestone Bar & Grill",
    "city": "Grand Blanc",
    "state": "MI",
    "time": "7:00p-11:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-10-05-117",
    "date": "2024-10-05",
    "venue": "Rocktober Fest at Short's Brewing Company",
    "city": "Bellaire",
    "state": "MI",
    "time": "Event time is 12p-10p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-10-03-118",
    "date": "2024-10-03",
    "venue": "Bikes & Boobs Breast Cancer Awareness Benefit <br>at Scooters Bar",
    "city": "Flint",
    "state": "MI",
    "time": "Event time is 6p-11p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-28-119",
    "date": "2024-09-28",
    "venue": "Blind Owl",
    "city": "Royal Oak",
    "state": "MI",
    "time": "9:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-27-120",
    "date": "2024-09-27",
    "venue": "Oktoberfest at Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-21-121",
    "date": "2024-09-21",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-13-122",
    "date": "2024-09-13",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-07-123",
    "date": "2024-09-07",
    "venue": "Au Gres Yacht Club",
    "city": "Au Gres",
    "state": "MI",
    "time": "8P-11P",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-09-06-124",
    "date": "2024-09-06",
    "venue": "Silver Lake Chicken Shack",
    "city": "Mears",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-31-125",
    "date": "2024-08-31",
    "venue": "Opening for Dancing Queen: An ABBA Salute <br>at Stix Bar",
    "city": "Ludington",
    "state": "MI",
    "time": "Starts at 7p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-30-126",
    "date": "2024-08-30",
    "venue": "Opening for Dancing Queen: An ABBA Salute <br>at Warner Vineyards",
    "city": "Paw Paw",
    "state": "MI",
    "time": "Starts at 7:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-18-127",
    "date": "2024-08-18",
    "venue": "Lapeer Days Festival (West Stage)",
    "city": "Lapeer",
    "state": "MI",
    "time": "4:30p-5:30p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-17-128",
    "date": "2024-08-17",
    "venue": "Ascend Sportsbook <br>at Soaring Eagle Casino",
    "city": "Mt. Pleasant",
    "state": "MI",
    "time": "10:00p-2:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-16-129",
    "date": "2024-08-16",
    "venue": "Hollywood Casino Toledo",
    "city": "Toledo",
    "state": "OH",
    "time": "9:00p-12:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-11-130",
    "date": "2024-08-11",
    "venue": "LoLo's Bar & Grill",
    "city": "Holland",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-10-131",
    "date": "2024-08-10",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-09-132",
    "date": "2024-08-09",
    "venue": "The Lotus Room<br>$10 admission",
    "city": "Norton Shores",
    "state": "MI",
    "time": "8:30p-11:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-03-133",
    "date": "2024-08-03",
    "venue": "Private Party <br>Pinckney 35th Class Reunion",
    "city": "Pinckney",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-02-134",
    "date": "2024-08-02",
    "venue": "Mash",
    "city": "East Lansing",
    "state": "MI",
    "time": "10:00p-1:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-08-01-135",
    "date": "2024-08-01",
    "venue": "Laingsburg Concert Series <br>at McClintock Park",
    "city": "Laingsburg",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-27-136",
    "date": "2024-07-27",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-13-137",
    "date": "2024-07-13",
    "venue": "Private Party <br>Long Lake Cloverdale Association",
    "city": "Delton",
    "state": "MI",
    "time": "7:30p-9:30p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-12-138",
    "date": "2024-07-12",
    "venue": "Ascend Sportsbook <br>at Soaring Eagle Casino",
    "city": "Mt. Pleasant",
    "state": "MI",
    "time": "10:00p-2:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-07-139",
    "date": "2024-07-07",
    "venue": "LoLo's Bar & Grill",
    "city": "Holland",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-06-140",
    "date": "2024-07-06",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-07-05-141",
    "date": "2024-07-05",
    "venue": "The Score",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-29-142",
    "date": "2024-06-29",
    "venue": "Original Gravity Brewing Co",
    "city": "Milan",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-28-143",
    "date": "2024-06-28",
    "venue": "The Green Door",
    "city": "Lansing",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-26-144",
    "date": "2024-06-26",
    "venue": "Walled Lake Summer Concert Series<br>at Hiram Sims Park",
    "city": "Walled Lake",
    "state": "MI",
    "time": "7:00p-9:00p",
    "category": "Concert Series",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-16-145",
    "date": "2024-06-16",
    "venue": "LoLo's Bar & Grill",
    "city": "Holland",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-15-146",
    "date": "2024-06-15",
    "venue": "South Haven Yacht Club",
    "city": "South Haven",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-08-147",
    "date": "2024-06-08",
    "venue": "Blessing of the Boats",
    "city": "Ludington",
    "state": "MI",
    "time": "Event @ 4:00p | Band @ 7:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-07-148",
    "date": "2024-06-07",
    "venue": "Private Event - Graduation Party",
    "city": "Pinckney",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-02-149",
    "date": "2024-06-02",
    "venue": "The Score",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-06-01-150",
    "date": "2024-06-01",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8p-12a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-31-151",
    "date": "2024-05-31",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8p-12a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-25-152",
    "date": "2024-05-25",
    "venue": "Private Event",
    "city": "Wolverine",
    "state": "MI",
    "time": "TBA",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-24-153",
    "date": "2024-05-24",
    "venue": "Gun Lake Casino",
    "city": "Wayland",
    "state": "MI",
    "time": "9:00p-12:00a",
    "category": "Casino",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-22-154",
    "date": "2024-05-22",
    "venue": "The Deck",
    "city": "Muskegon",
    "state": "MI",
    "time": "5p-8p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-18-155",
    "date": "2024-05-18",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-17-156",
    "date": "2024-05-17",
    "venue": "Cobblestone Bar & Grill",
    "city": "Grand Blanc",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-10-157",
    "date": "2024-05-10",
    "venue": "H.O.M.E. at The B.O.B.",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-04-158",
    "date": "2024-05-04",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-05-03-159",
    "date": "2024-05-03",
    "venue": "Winners Bar & Grill",
    "city": "Clinton Twp",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-04-27-160",
    "date": "2024-04-27",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-04-20-161",
    "date": "2024-04-20",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-04-06-162",
    "date": "2024-04-06",
    "venue": "Gravity Smokehouse",
    "city": "Holt",
    "state": "MI",
    "time": "8:00p-12:001",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-04-05-163",
    "date": "2024-04-05",
    "venue": "The Green Door",
    "city": "Lansing",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-30-164",
    "date": "2024-03-30",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-29-165",
    "date": "2024-03-29",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-15-166",
    "date": "2024-03-15",
    "venue": "Cobblestone Bar & Grille",
    "city": "Grand Blanc",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-09-167",
    "date": "2024-03-09",
    "venue": "The Green Door",
    "city": "Lansing",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-08-168",
    "date": "2024-03-08",
    "venue": "H.O.M.E. at The BOB",
    "city": "Grand Rapids",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-03-02-169",
    "date": "2024-03-02",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-02-17-170",
    "date": "2024-02-17",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-02-16-171",
    "date": "2024-02-16",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-02-10-172",
    "date": "2024-02-10",
    "venue": "Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-02-03-173",
    "date": "2024-02-03",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-01-27-174",
    "date": "2024-01-27",
    "venue": "Gravity Smokehouse",
    "city": "Holt",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2024-01-19-175",
    "date": "2024-01-19",
    "venue": "Cobblestone Bar & Grille",
    "city": "Grand Blanc",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-31-176",
    "date": "2023-12-31",
    "venue": "New Years Eve @ Wicks Park Bar & Grille",
    "city": "Saugatuck",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-30-177",
    "date": "2023-12-30",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-29-178",
    "date": "2023-12-29",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-23-179",
    "date": "2023-12-23",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-16-180",
    "date": "2023-12-16",
    "venue": "Vestal Inn",
    "city": "Belmont",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-12-09-181",
    "date": "2023-12-09",
    "venue": "Opening for Fast Fashion: The Depeche Mode Experience<br>The Vault",
    "city": "Saginaw",
    "state": "MI",
    "time": "Doors open at 7p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-25-182",
    "date": "2023-11-25",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-22-183",
    "date": "2023-11-22",
    "venue": "Thanksgiving Eve at Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-12-184",
    "date": "2023-11-12",
    "venue": "Private Event",
    "city": "East Lansing",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-11-185",
    "date": "2023-11-11",
    "venue": "Wicks Park Bar & Grille",
    "city": "Saugatuck",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-10-186",
    "date": "2023-11-10",
    "venue": "Crystal Bar",
    "city": "Westland",
    "state": "MI",
    "time": "9:00p-01:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-11-04-187",
    "date": "2023-11-04",
    "venue": "Rogue River Tavern",
    "city": "Rockford",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-10-28-188",
    "date": "2023-10-28",
    "venue": "The Kirby House",
    "city": "Grand Haven",
    "state": "MI",
    "time": "9:00p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-10-14-189",
    "date": "2023-10-14",
    "venue": "Gravity Smokehouse",
    "city": "Holt",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-10-07-190",
    "date": "2023-10-07",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-10-06-191",
    "date": "2023-10-06",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-30-192",
    "date": "2023-09-30",
    "venue": "Sherman's Lounge",
    "city": "Flint",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-29-193",
    "date": "2023-09-29",
    "venue": "Oktoberfest @ Original Gravity Brewing Co.",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-10:00p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-23-194",
    "date": "2023-09-23",
    "venue": "Auburn Hotel & Tavern",
    "city": "Auburn",
    "state": "MI",
    "time": "9:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-09-195",
    "date": "2023-09-09",
    "venue": "Pig Roast at Birch Run Moose Lodge",
    "city": "Birch Run",
    "state": "MI",
    "time": "Event starts @ 3p, Music @ 6:30p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-08-196",
    "date": "2023-09-08",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-02-197",
    "date": "2023-09-02",
    "venue": "Au Gres Yacht Club",
    "city": "Au Gres",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Club Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-09-01-198",
    "date": "2023-09-01",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-08-19-199",
    "date": "2023-08-19",
    "venue": "Sherman's Lounge",
    "city": "Flint",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-08-18-200",
    "date": "2023-08-18",
    "venue": "Private Event - Wedding",
    "city": "Wolverine",
    "state": "MI",
    "time": "",
    "category": "Wedding",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-08-12-201",
    "date": "2023-08-12",
    "venue": "LoLo's Bar & Grill",
    "city": "Holland",
    "state": "MI",
    "time": "4:00p-8:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-08-11-202",
    "date": "2023-08-11",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9p-1a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-28-203",
    "date": "2023-07-28",
    "venue": "Winners Bar & Grill",
    "city": "Clinton Twp",
    "state": "MI",
    "time": "9p-1a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-22-204",
    "date": "2023-07-22",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-21-205",
    "date": "2023-07-21",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-15-206",
    "date": "2023-07-15",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-14-207",
    "date": "2023-07-14",
    "venue": "Sherman's Lounge",
    "city": "Flint",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-13-208",
    "date": "2023-07-13",
    "venue": "Opening for Double Vision - The Foreigner Experience <br>at District 142",
    "city": "Wyandotte",
    "state": "MI",
    "time": "",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-07-01-209",
    "date": "2023-07-01",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-24-210",
    "date": "2023-06-24",
    "venue": "Private Party",
    "city": "Pinckney",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-17-211",
    "date": "2023-06-17",
    "venue": "Original Gravity Brewing Co.",
    "city": "Milan",
    "state": "MI",
    "time": "4:00p-7:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-16-212",
    "date": "2023-06-16",
    "venue": "Private Party",
    "city": "Howell",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-10-213",
    "date": "2023-06-10",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-09-214",
    "date": "2023-06-09",
    "venue": "The Draft Bar & Grille",
    "city": "Swartz Creek",
    "state": "MI",
    "time": "9:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-03-215",
    "date": "2023-06-03",
    "venue": "Club Canton",
    "city": "Canton",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-06-02-216",
    "date": "2023-06-02",
    "venue": "Club Canton",
    "city": "Canton",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-05-19-217",
    "date": "2023-05-19",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-05-09-218",
    "date": "2023-05-09",
    "venue": "Private Corporate Party",
    "city": "Detroit",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-04-29-219",
    "date": "2023-04-29",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-04-28-220",
    "date": "2023-04-28",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-04-22-221",
    "date": "2023-04-22",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-04-21-222",
    "date": "2023-04-21",
    "venue": "Hell Saloon",
    "city": "Hell",
    "state": "MI",
    "time": "8:00p-12:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-04-01-223",
    "date": "2023-04-01",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-03-31-224",
    "date": "2023-03-31",
    "venue": "Opening for Hairball @ Lansing Center",
    "city": "Lansing",
    "state": "MI",
    "time": "Doors open at 7p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-03-24-225",
    "date": "2023-03-24",
    "venue": "Winners Bar & Grill",
    "city": "Clinton Towship",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-03-11-226",
    "date": "2023-03-11",
    "venue": "Private Birthday Party",
    "city": "Lansing",
    "state": "MI",
    "time": "",
    "category": "Private Event",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-03-04-227",
    "date": "2023-03-04",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-03-03-228",
    "date": "2023-03-03",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-02-25-229",
    "date": "2023-02-25",
    "venue": "FFA Alumni Hootenany Fundraiser",
    "city": "Springport",
    "state": "MI",
    "time": "5:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-01-28-230",
    "date": "2023-01-28",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2023-01-27-231",
    "date": "2023-01-27",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-12-30-232",
    "date": "2022-12-30",
    "venue": "Sherman's Lounge",
    "city": "Flint",
    "state": "MI",
    "time": "8:30p-12:30a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-12-23-233",
    "date": "2022-12-23",
    "venue": "Double Clutch Bar",
    "city": "Okemos",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-12-16-234",
    "date": "2022-12-16",
    "venue": "Double Clutch Bar",
    "city": "Okemos",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-12-09-235",
    "date": "2022-12-09",
    "venue": "Double Clutch Bar",
    "city": "Okemos",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-12-02-236",
    "date": "2022-12-02",
    "venue": "Double Clutch Bar",
    "city": "Okemos",
    "state": "MI",
    "time": "7:00p-10:00p",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-11-26-237",
    "date": "2022-11-26",
    "venue": "Sherman's Lounge",
    "city": "Flint",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-11-12-238",
    "date": "2022-11-12",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-10-22-239",
    "date": "2022-10-22",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-10-21-240",
    "date": "2022-10-21",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-10-08-241",
    "date": "2022-10-08",
    "venue": "Private Wedding Reception",
    "city": "Howell",
    "state": "MI",
    "time": "",
    "category": "Wedding",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-10-07-242",
    "date": "2022-10-07",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-09-30-243",
    "date": "2022-09-30",
    "venue": "Oktoberfest @ Original Gravity Brewing Co.",
    "city": "Milan",
    "state": "MI",
    "time": "6:00p-9:00p",
    "category": "Festival",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-09-23-244",
    "date": "2022-09-23",
    "venue": "Private Wedding",
    "city": "St. Joseph",
    "state": "MI",
    "time": "",
    "category": "Wedding",
    "public": false,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-09-10-245",
    "date": "2022-09-10",
    "venue": "Tanglewood Winery",
    "city": "Holland",
    "state": "MI",
    "time": "5:00p-8:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-09-09-246",
    "date": "2022-09-09",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-08-20-247",
    "date": "2022-08-20",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-08-19-248",
    "date": "2022-08-19",
    "venue": "Back to Bricks at Trapper Joe's <br>feat. Rev. Right-Time",
    "city": "Burton",
    "state": "MI",
    "time": "7:00p-11:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-08-12-249",
    "date": "2022-08-12",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-08-05-250",
    "date": "2022-08-05",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-07-30-251",
    "date": "2022-07-30",
    "venue": "The Exchange",
    "city": "Lansing",
    "state": "MI",
    "time": "9:30p-1:00a",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-07-04-252",
    "date": "2022-07-04",
    "venue": "4th of July Celebration @ McCurdy Park",
    "city": "Corunna",
    "state": "MI",
    "time": "8:00p-10:00p",
    "category": "Live Music",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-07-02-253",
    "date": "2022-07-02",
    "venue": "Itty Bitty Bar",
    "city": "Holland",
    "state": "MI",
    "time": "9:00p-1:00a",
    "category": "Bar / Pub",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  },
  {
    "id": "show-2022-06-18-254",
    "date": "2022-06-18",
    "venue": "Original Gravity Brewing Co.",
    "city": "Milan",
    "state": "MI",
    "time": "4:00p-7:00p",
    "category": "Brewery",
    "public": true,
    "featured": false,
    "ticketLink": "",
    "website": "",
    "image": "",
    "tags": [],
    "notes": ""
  }
];
